[package]
name = "gtk-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = "0.14.9"
gio = "0.14.8"
glib = "0.14.8"
pango = "0.14.8"
gtk = "0.14.3"